name: Code Inspection

on: ['push', 'pull_request', 'workflow_dispatch']

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Qodana Code Inspection
        uses: JetBrains/qodana-action@v2.0-eap
      - name: Upload Report
        uses: actions/upload-artifact@v2.2.3
        with:
          name: report
          path: ${{ github.workspace }}/qodana
